services:
  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog.Api/Dockerfile
  
  catalog.db:
    image: postgres:13-bullseye
    container_name: catalog.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDB
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /docker/eshop/catalog/data:/var/lib/postgresql/data